
server:
  port: 12889
  servlet:
    context-path:
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        auto-create: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          ddl-auto: create-drop
    generate-ddl: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres


